apiVersion: v1
kind: ConfigMap
metadata:
    name: mycnf
data:
    mycnf: |
      [mysqld]
        log_bin_trust_function_creators = 1
        innodb_file_per_table           = 1
        max_allowed_packet              = 256M
        innodb_buffer_pool_size         = 8G
        innodb_buffer_pool_chunk_size   = 1G
        innodb_buffer_pool_instances    = 8
        innodb_log_file_size            = 2G
        innodb_flush_method             = O_DIRECT
        innodb_flush_log_at_trx_commit  = 2
        explicit_defaults_for_timestamp = 1
